server:
  port: 9090

spring:
  application:
    name: fhir-graphql-api

  datasource:
    url: jdbc:mysql://${FHIR_DB_HOST:localhost}:${FHIR_DB_PORT:3306}/fhir_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${FHIR_DB_USERNAME:root}
    password: ${FHIR_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  graphql:
    http:
      path: /graphql/fhirapi/patient
    graphiql:
      enabled: true
      path: /graphiql

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${FHIR_JWT_SECRET}
  expiration: 1800000
