type AppointmentResponse {
    id: ID!
    patientId: ID!
    doctorId: ID!
    slotId: ID!
    status: String!
    reason: String
    notes: String
    appointmentDateTime: String!
    createdAt: String!
}

input CreateAppointmentInput {
    patientId: ID!
    doctorId: ID!
    slotId: ID!
    reason: String
    appointmentTime: String!
} 

type Query {
    getAppointmentById(appointmentId: ID!): AppointmentResponse
    getAppointmentByPatient(patientId: ID!, page: Int, size: Int): [AppointmentResponse]
    getAppointmentsByDoctor(doctorId: ID!, page: Int, size: Int): [AppointmentResponse]
}

type Mutation {
    createAppointment(request: CreateAppointmentInput!): AppointmentResponse
}
