Services:
  doctor-service:
    build: .
    container_name: doctor-service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/doctor_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      ports:
      - "8490:8490"
      depends_on:
        mysql:
          condition: service_healthy
      networks:
      - doctor-database-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8490/actuator/health || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 15s
    
  mysql:
    image: mysql:8.0
    container_name: doctor-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doctor_db
      MYSQL_USER: doctor_user
      MYSQL_PASSWORD: doctor_pass
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - doctor-database-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 3

networks:
  doctor-database-network:
    driver: bridge

volumers:
  mysql-data:
    driver: local