server:
  port: 9090

spring:
  application:
    name: fhir-graphql-api
  
  datasource:
    url: jdbc:mysql://localhost:3306/fhir_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  
  graphql:
    http:
      path: /graphql/fhirapi/patient
    graphiql:
      enabled: true
      path: /graphiql

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 1800000
